version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install
  build:
    commands:
      - npx cypress run --headless
  post_build:
    commands:
      - npx cypress run --record --key YOUR_CYPRESS_RECORD_KEY # Optional: Record test results
artifacts:
  files:
    - '/*'
  discard-paths: yes
